### ISSUE TITLE
Open Community Working Meeting 2023-01-16 - 14:00 PT

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#294]
# Open Community Working Meeting 2023-01-16 14:00 PT

## Agenda

| Topic | Owner | Decision/NextStep |
| -- | -- | -- |
| Review last call's action items  | [facilitator] | All action items were reviewed. |
| Usage of "agenda" label for PRs to be discussed in the meeting | @Relequestual |- Creation of the label "agenda" to allow tagging of issues or PR to be discussed in the OCWM and use Actions to get them included in the agenda. <br />- As a next iteration, explore ways to tag comments to get them included as well|
| Analytics for website?<br/>Currently we use Google Analytics. We could move to [Plausible](https://plausible.io/), but it would cost us $19 a month or $190 a year. (You can self-host, but that takes some effort) | @Relequestual |- The feedback has been positive by all attendees. Therefore a new issue will be created to gather feedback from the Community.<br />- We should validate with OpenJS Foundation what support they can provide to get the tool.|
| JSON Schema LinkedIn profile? | @benjagm | Check availability of the profile, pricing, and team features |
| Let's upload the recordings of all community meetings to Youtube | @benjagm | The feedback has been positive by all attendees, but due to the importance of the Topic a new issue will be created to gather feedback from the Community. |

AOB?  
If you want to discuss any other business not on the agenda, please add comments during the meeting.  
If we do not complete the agenda, your discussion item will likely be rolled over to the next call.

## Highlights

* We had a great discussion about how positive might be tagging issues, PR, or comments to get them automatically included in the agenda through GitHub automations. gregsdennis shared an example of how to get action working in multiple repositories of in the same organization. (See comments)
* We discussed different alternatives to Plausible including Mamoto and Google Analytics but we agreed on Plausible as the best option. @jviotti  Shared his positive experience using the tool.
* Linkedin seems to be a great addition to the Social Media strategy, but we need to confirm profile availability and pricing. 
* We agreed on the positive implications of uploading the recording of future sessions to Youtube, but creating a new issue will be necessary to get maximum consensus within the Community. @benjagm proposed asking to attendees before every meeting if they are ok with recording and sharing on Youtube.
* We discussed the positive implications of dissociating the meetings and recordings from Postman.
* @jviotti shared the progress with the article about the history of JSON Schema.

## Action Items

  - [x] @benjagm will create the new tag and will build the first automation to get items included in the agenda.<br/>Related issue: #301.
  - [x] @Relequestual will check with OpenJS Foundation what support they can provide to get a Plausible account.
  - [x] @Relequestual will create an issue to get the Community feedback about using Plausible.<br/>Related issue: #300 
  - [x] @benjagm will confirm the pricing and availability of the linkedin profile.<br/>Related issue: #302
  - [x] @benjagm will create an issue to gather feedback from the Community about the benefits of sharing the recording of future sessions on Youtube, detailing our proposal of asking attendees before every meeting if they are ok with recording and sharing.<br/>Related issue: #303

## Attendees

|    Account    |
| :-----------: |
|   @Relequestual   |
|   @jdesrosiers  | 
|   @gregsdennis  | 
|   @jviotti   | 
|   @benjagm  | 

Notes:

Agenda Items rolling over:
- list

Recording: [link](https://postman.zoom.us/rec/share/IWJtAMim0YoA3wdKQrAihdSpFUXo-AWbzEtNNjCa_zR2y9Df_QCGIoopSCjNu642.Djduwemf4nwzRuuc)

**Comment by gregsdennis** [comment]
Re: _Usage of "agenda" label for PRs to be discussed in the meeting_

https://blog.marcnuri.com/triggering-github-actions-across-different-repositories

Shows how to use actions in one repository to trigger an action in another repository.  We could set this up to have actions in all of our repos that trigger an action in this repo to perform an action.

**Comment by gregsdennis** [comment]
@benjagm We also wanted to look into dissociating the meetings and recordings from Postman.

**Comment by benjagm** [comment]
100% @gregsdennis. Thanks for pointing it out. I updated the highlights to get this point included.

**Comment by benjagm** [comment]
Closing this issue as all tasks are completed. Thanks for your contributions!
