### ISSUE TITLE
Open Community Working Meeting 2023-05-22 - 14:00 PT

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#389]
# Open Community Working Meeting 2023-05-22 - 14:00 PT

📺 [Recording](https://youtu.be/QvQ9RVHws1E)

⏪ [Go To Previous Meeting](https://github.com/json-schema-org/community/issues/385)

Agenda:

| Topic | Owner | Decision/NextStep |
| -- | -- | -- |
| Review last call's action items  | [facilitator] |
| The Spec PR [#1400](https://github.com/json-schema-org/json-schema-spec/pull/1400) is looking for reviews | @benjagm | We expect others to review the PR as soon as they have time.
The Spec ADR [#1406](https://github.com/json-schema-org/json-schema-spec/pull/1406) is looking for reviews |@benjagm | We found that we still don't have agreement on some aspects of the discussion, therefore the ADR will be closed for now.
| We have GSoC interested in mentoring and I think running a small mentoring program like [this](https://www.sktime.net/en/latest/get_involved/mentoring.html) can be beneficial | @benjagm | We don't have volunteers and resources for running a mentoring program, therefore we'll provide mentoring but without establishing a formal program for now. |

Action items:
- [x] @gregsdennis to close the Spec ADR [#1406](https://github.com/json-schema-org/json-schema-spec/pull/1406) to continue the discussion until having consensus.
- [x] @Relequestual will share his objections in #384 so that we can discuss his hesitations.
- [x] The team will review the Spec PR [#1400](https://github.com/json-schema-org/json-schema-spec/pull/1400).

Notes:

- The meeting started wit the team reviewing the action items of the last session.
- Greg explained the purpose of the PR #1400. He shared that he will send another PR as soon as this get merged, this is way getting reviews will be really helpful.
- The team spent most of the time discussing the proposed ADR for how meta-schemas and dialects work under a stable specification:
     - We discussed that the ADR came from several discussions that started with whether to include `unevaluatedProperties: false` in the meta-schema and ended up making decisions on other things as well.
     - @gregsdennis  and @Relequestual  discussed the use of a perpetually updated metaschema versus providing snapshotted versions with unique identifiers. The team didn't agree on anything for this topic.  @Relequestual will share his objections in writing so that we can discuss his hesitations.
     - The team discussed the evolution of the JSON schema specification and the challenges of maintaining snapshots of the Metaschemas. They debated the need for unique IDs in the Metaschemas and the importance of having a stable URI for the dollar schema keyword. 
     - The team also discussed finalizing the developer process for publishing new versions of the spec, including decisions on metaschemas and dialects. They also debated the definition of unknown keywords and their interoperability between implementations.
     - The group discussed the compatibility of an open metaschema and whether it should be forward compatible. They ultimately decided to close the current ADR and revisit the topic in the future with more input from all members.

 - @benjagm proposed a mentoring program for contributors, but @Relequestual  expressed concern about the amount of time it would take up and suggested focusing on higher priority tasks. The group discussed the idea and decided to take a more low-key approach and silently reach out to a few people to see how it goes and  evaluate the success in the future.

  - Before closing the session @Relequestual  mentioned attending a conference about a grant issued by the Sovereign Tech Fund to the OpenJS Foundation, which may provide opportunities for DevOps work. 

Agenda Items rolling over:
- list

## Attendees

|    Account    |
| :-----------: |
|   @Relequestual   | 
|   @benjagm  | 
|   @gregsdennis  | 
|   @Julian  |

**Comment by benjagm** [comment]
Closing this issue as all tasks are completed. Thanks for your contributions!
