### ISSUE TITLE
Open Community Working Meeting 2023-06-19 - 14:00 PT

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#411]
## Open Community Working Meeting 2023-06-19 - 14:00 PT

📺 [See Recording](https://youtu.be/NbOqcqAxpxk)

⏪ [Go To Previous Meeting](https://github.com/json-schema-org/community/issues/400)

Agenda: 

| Topic | Owner | Decision/NextStep |
| -- | -- | -- |
| Review last call's action items  | [facilitator] |
| Issue [#415](https://github.com/json-schema-org/community/issues/415) - Complete the new version of the Spec| @gregsdennis<br> @jdesrosiers<br>@benjagm  | @jdesrosiers will add his comments to the issue. |
| https://github.com/json-schema-org/json-schema-spec/issues/1414 - Contributing guide file is outdated | @Relequestual | @benjagm will update the guidelines as part of issue #410.
| https://github.com/json-schema-org/community/pull/416 - New TSC channels | @benjagm | Once the PR is reviewed we will provide one week of warning before archiving the channel.

Action items:
- [x] @jdesrosiers will add his comments to the issue #415 .
- [x] @benjagm to proceed with updating the Contributing guidelines of the Specification as part of #410 .
- [x] Once #416 is merged @benjagm will communicate the archive of the `#collaborators` channel one week in advance to allow everyone to share concerns.

Notes:
- The team reviewed the action items from the previous meeting and discussed topics such as the specification scope, the specification contribution guidelines, and the creating new channels for the technical steering committee.
- The team continued the discussion of identifying the scope of the next Spec release. While @gregsdennis provided his comments in the issue [#415](https://github.com/json-schema-org/community/issues/415), @jdesrosiers committed to add his comments in the upcoming days.
- @Relequestual suggested updating the contributing document of the Specification repository and remove some of the outdated information [issue #1414]( https://github.com/json-schema-org/json-schema-spec/issues/1414). @jdesrosiers  mentioned that we need to clarify the spec development process yet. @benjagm committed to make the changes as part of Refine the contributor journey - issue #410.
- @benjagm asked for feedback on how to better proceed with archiving `#collaborators` channel when creating the new tsc channels ( See #416 ). @Relequestual suggested linking to the relevant issue before archiving the channel and the team agreed on giving a week of warning before doing so.

## Attendees

|    Account    |
| :-----------: |
|   @jdesrosiers     | 
|   @Relequestual   | 
|   @benjagm  |

**Comment by benjagm** [comment]
I just opened a PR with a new version of the contributing guidelines of the Spec. I am marking as completed that action item.
https://github.com/json-schema-org/json-schema-spec/pull/1416

**Comment by benjagm** [comment]
The action item for @jdesrosiers has been marked as completed.

See https://github.com/json-schema-org/community/issues/415#issuecomment-1599715498

**Comment by benjagm** [comment]
Closing this issue as all tasks are completed. Thanks for your contributions!
