### ISSUE TITLE
Open Community Working Meeting 2023-07-03 - 14:00 PT

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#429]
## Open Community Working Meeting 2023-07-03 - 14:00 PT

📺 [See Recording](https://youtu.be/u03xh3Y3ZYE)

⏪ [Go To Previous Meeting](https://github.com/json-schema-org/community/issues/420)

Agenda: 

| Topic | Owner | Decision/NextStep |
| -- | -- | -- |
| Review last call's action items  | [facilitator] |
| PR [#5](https://github.com/json-schema-org/.github/pull/5) Update the Code of Conduct | @benjagm  | @benjagm to provide comments in the PR |
| https://github.com/json-schema-org/community/issues/418 - Research of existing implementations by language | @Relequestual | @Julian to modify the plan of #418 to add action items to describe what we understand as high quality implementations. |
| https://github.com/json-schema-org/community/issues/412 - Strategy for engaging implementers | @Relequestual | @benjagm to modify the plan #412 to add gamification and proactive engagement with implementers. |
| https://github.com/json-schema-org/community/issues/410 - Refine the contributor journey | @Relequestual | @benjagm to add action item in #410 to define success metrics. |
| https://github.com/json-schema-org/community/issues/408 - Identify a list of critical interfaces that implementations should have and empower implementers with better resources | @Relequestual | Comments added in the Issues |
| Convert the spec to markdown (details below) | @gregsdennis| We need to vote [here](https://github.com/json-schema-org/json-schema-spec/issues/1335)  what option is better |

You can have a PR or an issue added to this agenda by just adding them the `agenda` label.

AOB?
If you want to discuss any other business not on the agenda, please add comments during the meeting.
If we do not complete the agenda, your discussion item will likely be rolled over to the next call.

Action items:
- [x] @benjagm to add comments in the PR [#5](https://github.com/json-schema-org/.github/pull/5) to reduce references to IETF.
- [x] @Julian to modify the plan of #418 to add action items to describe what we understand as high quality implementations.
- [x] @benjagm to modify the plan #412 to add gamification and proactive engagement with implementers.
- [x] @benjagm to add action item in #410 to define success metrics.
- [x] Everyone: Vote for any of the options suggested [here](https://github.com/json-schema-org/json-schema-spec/issues/1335) 

Notes:
* The team discussed various action items from the previous session, including modifying the charter, creating an issue for feedback, and checking with a GSoC Contributor. They also reviewed a pull request in the community repo and concluded that it was fine to merge with some minor changes to remove references to the IETF.
* The team discussed issue #418 including the importance of defining high-quality implementations, and the plan to research existing implementations by language. They also considered the possibility of writing a report on the ecosystem and exploring ways to provide additional resources for implementers.
* @gregsdennis  and @jdesrosiers discussed their hesitation to create documentation for implementers, as they believed it could limit creativity and influence the architecture of implementations. However, they agreed that providing non-prescriptive resources to help implementers get started would be beneficial. 
* The team discussed #412 and @gregsdennis suggested to include gamification and more active engagement with implementers and reaching out to them directly instead of relying on passive methods like website updates and badges. They also considered different communication channels and the potential impact of excessive outreach. 
The team provided good feedback regarding the plan in #410 . @benjagm agreed on adding an action item to confirm the success metrics.
* The team discussed #408. They considered options such as connect this with the self-reporting of the implementers strategy. Approaches like creating a Google form to gather information and store the info in a JSON file in the repository were commented. The team suggested to check the list of interfaces again a group well known implementations. @benjagm suggested being transparent and creating a working group to invite others to join their research efforts, with the hope of achieving more positive results.
* The team discussed the next steps for editing the spec and converting it to Markdown. The team discussed the advantages and challenges of using different formats (markdown vs kramdown) for their project. They decided to gather feedback and take a vote before making a final decision. 

## Attendees

|    Account    |
| :-----------: |
|   @jdesrosiers     | 
|   @Relequestual   | 
|   @benjagm  | 
|   @gregsdennis    |

**Comment by gregsdennis** [comment]
Converting the spec to markdown options:

1. https://github.com/json-schema-org/json-schema-spec/pull/1357 (simple markdown)
2. https://github.com/json-schema-org/json-schema-spec/pull/1412 (IETF-style RFC kramdown)
3. Just rewrite it from scratch

I think we should leave Relative JSON Pointer as is considering it's still IETF-published for now.

**Comment by benjagm** [comment]
I left a comment in [PR 5](https://github.com/json-schema-org/.github/pull/5) As agreed as action item.

**Comment by benjagm** [comment]
As agreed, I updated #410 to add an action item to confirm the metrics.

**Comment by benjagm** [comment]
I have modified the Program design section of issue #412 to add action items to include gamification and proactive engagement with implementers.

**Comment by Relequestual** [comment]
> The team discussed various action items from the previous session, including modifying the charter, creating an issue for feedback, and checking with a GSoC Contributor. They also reviewed a pull request in the community repo and concluded that it was fine to merge with some minor changes to remove references to the IETF.

This is not accurate. We agreed on the call to keep the reference to the IETF, but that we would add that we are not part of the IETF at this point in time, but we follow the ethos found in the best practices from the linked document.

**Comment by benjagm** [comment]
Completed
