### ISSUE TITLE
Open Community Working Meeting 2021-09-17

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/community#45]
### Open Community Working Meeting 2021-09-17 - 14:00 UTC

Zoom Meeting link: https://postman.zoom.us/j/84578640198

**Agenda**

| Topic | Owner | Decision/NextStep |
| -- | -- | -- |
| Review last call's action items #42 | @relequestual | We discussed json-schema-org/json-schema-spec#1120 which was an agenda item from last week. @Relequestual eventually understood why the hyper-schema meta-schemas for 2019-09 were broken. We agreed to seek feedback on @jdesrosiers proposed solutions. |
| Add propertyDependencies keyword json-schema-org/json-schema-spec#1082 | @jdesrosiers | We agreed to consider this new keyword for the next feature release. It should be added to the associated milestone. |
| Add optional keyword json-schema-org/json-schema-spec#1112 | @Altreus / @jdesrosiers | We agreed we liked the general idea, but the name needed to change. Jason suggested we ask the community. |

**If you want to add items to the agenda, please leave comments before the meeting.**

**AOB?**
If you want to discuss any other business not on the agenda, please add comments during the meeting.
If we do not complete the agenda, your discussion item will likely be rolled over to the next call. 

**Action items:**

- [x] Seek feedback form wider community of JSON Hyper Schema users relating to json-schema-org/json-schema-spec#1120 - @Relequestual
- [ ] Consider json-schema-org/json-schema-spec#1082 for next feature change release. Add it to the milestone - Anyone (or @Relequestual)
- [x] Ask the community what to call the new keyword proposed in json-schema-org/json-schema-spec#1112 - @Relequestual

**Notes:**
Pre-meeting note: @Relequestual - I've not been able to carry out the action items from the last call due to focusing on writing a talk for the API Specifications Conference.

Agenda Items rolling over: None

Recording: https://postman.zoom.us/rec/share/zfqCR96xXnFNsS0HcukhGRoFTYUqokR3-upxjF_PuhemkPmP1Mwi7suRbRSGMJFQ.Opk84hW3gvpr5XCS?startTime=1631887415000

Highlights: https://grain.co/share/story/4752d42b-4561-405d-9c7f-cdd14cf8e9f9/L7gOvtFvK1LNSpnBOoXP3dfgIsJurVyHQ7eDL8Pg

**(We are trialing "highlights" from Grain. Zoom also has highlights. Please direct your feedback on either or both to @Relequestual via Slack, Twitter, or here.)**

**Comment by karenetheridge** [comment]
Please could you extend a specific invitation to the people who submitted the change proposals? They may want to be there to discuss their issue, if given the chance.

**Comment by Relequestual** [comment]
@karenetheridge thanks for highlighting I hadn't done this correctly! I've now mentioned @Altreus. I hope that will be enough. I'll see if I can reach them any other way too.

**Comment by jdesrosiers** [comment]
This might not be the right time to discuss the `propertyDependencies` proposal. @gregsdennis was the one who was against it and I don't think this meeting time is friendly to his timezone. The whole point of discussing it is the find common ground with him. It wouldn't be very useful to have a discussion with everyone who already agrees.

**Comment by gregsdennis** [comment]
My objection to `propertyDependencies` is the special case nature.  I don't feel it's generic enough to be considered for the proper spec. I think it should be in a secondary vocab.

That said, I seem to be in a significant minority in this.  Specifically that minority consists of just me.  I don't think that warrants holding up the discussion.  Feel free to carry on.
