### ISSUE TITLE
Define a survey for implementers to understand their pain points, concerns and needs.

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#451]
As part of the strategy to engage implementers defined in #412, we'd like to design a Survey for implementers to understand their pain points, concerns and needs and design a program to engage with them.

Jobs to be done:
- [x] Research similar surveys.
- [x] Design sections and questions.
- [ ] Validate survey with early adopters.
- [ ] Build survey.

**Comment by benjagm** [comment]
Similar surveys:
* https://github.com/cncf/surveys/blob/main/maintainer/2019/maintainer-survey-questions-2019-h1.md
* [2022-open-source-software-supply-chain-survey.pdf](https://github.com/json-schema-org/community/files/12122284/2022-open-source-software-supply-chain-survey.pdf)
* [2023-open-source-maintainer-survey.pdf](https://github.com/json-schema-org/community/files/12122287/2023-open-source-maintainer-survey.pdf)
* [2021_Tidelift_Maintainer_Survey_FINAL.pdf](https://github.com/json-schema-org/community/files/12122290/2021_Tidelift_Maintainer_Survey_FINAL.pdf)
* [2017 GitHub Open Source Survey](https://github.com/json-schema-org/community/files/12122298/questionnaire.txt)

**Comment by benjagm** [comment]
This is the work in progress version of the Survey: [Survey](https://docs.google.com/document/d/1gpyeJkHvnSpx0AC59XO7K91usG3TVfiEaM4mEz8pM4Y/edit?usp=sharing) 

The sections I am suggesting are:
- Questions to build the Implementer’s profile
- Questions to understand the types of implementations
- Questions to get to know the implementations’ engagement and governance
- Questions to get to know the Implementations’ status
- Questions to understand the implementer's challenges and pain points
- Questions to identify areas of improvement
- Questions to present opportunities


Happy to get feedback.

**Comment by gregsdennis** [comment]
Maybe we should have a brief definition of what we consider to be an "implementation."  For example, I have _JsonSchema.Net_ to provide validation/annotation functionality, but I also have as extensions to that library _JsonSchema.Net.Generation_ and _JsonSchema.Net.DataGeneration_.  These provide different functionality, so does that make them different implementations?

**Comment by benjagm** [comment]
> Maybe we should have a brief definition of what we consider to be an "implementation"

This would be amazing. In the new website we are going to publish the glossary and it would be the perfect place for this definition.

**Comment by benjagm** [comment]
Another survey example by CHAOSS Community.
[Help the CHAOSS project improve our tools and metrics.pdf](https://github.com/json-schema-org/community/files/12715101/Help.the.CHAOSS.project.improve.our.tools.and.metrics.pdf)
[Survey_ Help the CHAOSS project improve our tools and metrics￼ - CHAOSS.pdf](https://github.com/json-schema-org/community/files/12715103/Survey_.Help.the.CHAOSS.project.improve.our.tools.and.metrics.-.CHAOSS.pdf)

**Comment by gregsdennis** [comment]
Interestingly, the definition of an "implementation" came up again in a separate context.  Here's the result: https://github.com/json-schema-org/json-schema-spec/issues/1440

**Comment by benjagm** [comment]
A first draft of the implementers survey is ready to review here:

(https://docs.google.com/document/d/1gpyeJkHvnSpx0AC59XO7K91usG3TVfiEaM4mEz8pM4Y/edit?usp=sharing)

**Comment by Relequestual** [comment]
@benjagm What are the next steps/timelines for this? =]

**Comment by benjagm** [comment]
> What are the next steps/timelines for this?

The whole plan is available in #412, it contain steps but it doesn't contain dates.
