### ISSUE TITLE
Define a list of common resources for refining the Contribution journeys

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#508]
Elements to consider:
- Readme contributing paragraph template
- Contributing template
- Standarize current Contributors approach
- Are labels standard?
- handbook.
- We have a recognition strategy for Slack, Social Media and Github

Deliverables:
- [x] Create triage.md #538 
- [x] Update org wide /community/CONTRIBUTING.md #538 
- [x] Review the contributing of the template repository
- [x] Template of contributors section for readme of all repositories
- [x] Note on how we will show contributors

Expected location: community\docs\handbook

**Comment by benjagm** [comment]
We'll start adding assets here as soon as we standarize the website repository.

**Comment by benjagm** [comment]
We'll use this template for the contributors section in all repositories:
``` 
### Contributors

Thanks goes to these wonderful people who contributed to this website:
<a href = "https://github.com/json-schema-org/REPO-NAME/graphs/contributors">
  <img src = "https://contrib.rocks/image?repo=json-schema-org/REPO-NAME"/>
</a>

<sub>Made with [contributors-img](https://contrib.rocks).</sub>

### Financial Contributors

Become a financial contributor and help us sustain our community. [[Contribute](https://opencollective.com/json-schema/contribute)]`

## Connect with the JSON Schema Community

<p align="left">
    <a href="https://json-schema.org/slack" target="blank">
      <img align="center" src="https://img.icons8.com/color/48/null/slack-new.png" alt="JSON Schema Slack" height="30" width="40" />
    </a>
    <a href="https://twitter.com/jsonschema" target="blank">
      <img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/twitter.svg" alt="JSON Schema Twitter" height="30" width="40" />
    </a>
    <a href="https://www.linkedin.com/company/jsonschema" target="blank">
      <img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/linked-in-alt.svg" alt="JSON Schema LinkedIn" height="30" width="40" />
    </a>
    <a href="https://www.youtube.com/@JSONSchemaOrgOfficial" target="blank">
      <img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/youtube.svg" alt="JSON Schema YouTube" height="30" width="40" />
    </a>
</p>
```

**Comment by benjagm** [comment]
We won't use all-contributors for the moment. We'll use the format shared before.
