### ISSUE TITLE
JSON Schema at API Days Paris 2023

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#528]
### Purpose:
The purpose of this GitHub issue is to coordinate and document the planning and execution of our on-site presence as partner Community at API Days Paris 2023. This will serve as a central hub for collaboration, ensuring a seamless and successful participation in the event.

### About the Conference:
Event Name: API Days Paris 2023
Date: 6-8 December
Location: Paris
Audience: API Practitioners, Business representatives, API vendors and other profiles.

### Goals:
**Community Engagement:**
 Foster meaningful interactions with conference attendees to strengthen our open source community connections.

**Project Visibility:**
 Increase brand visibility through strategic booth placement, branded materials, and active participation in conference sessions.

**Attract prospect adopters and sponsors:**
 Identify potential adopters and sponsors.

### Action Plan (Checklist):
**Pre-Conference Planning:**
 - [x] Define Objectives
    - Learn from this participation and explore to host a JSON Schema track for 2024.
    - Have meaningful conversations with attendees, JSON Schema users and organizations.
    - Attract prospect adopters and sponsors. 
 - [x] Define attending team.
    @Relequestual and @benjagm will be staffing de booth, however everyone is welcome to join us onsite.
 - [x] Define booth Logistics.
    @benjagm will bring stickers, a stand-up banner and socks.
    @Relequestual will bring beer mats.
    We just need a table cloth, but considering that it will be a joint booth we are in discussions to produce something together with AsyncAPI and OpenAPI.
 - [x] Prepare Swag
 - [x] Booth Setup. 
    - Generate a QR to fill the adopters form.
    - Decide the prize and prepare  a raffle.
 - [x] Define Success metrics
    - Attract 5 prospect adopters.
    - Have 5 meaningful conversations.
    - Start discussions to host a JSON Schema track.
 - [x] Announce with the Community. This has been published in Slack, GitHub and Open Collective
 - [x] Booth shifts.(To be aligned onsite with AsyncAPI Team)

**On-Site Execution:**
 - [x] Engagement Strategy
 - [x] Collect success metrics
 
**Post-Conference Evaluation:**
 - [x] Metrics Evaluation
 - [x] Follow-up with contacts
 - [x] Share blog with report
 
We invite the community and the team to provide feedback on this plan. Whether you have suggestions, concerns, or additional insights, your input is invaluable to the success of our participation in API Days Paris.

Thanks!

**Comment by benjagm** [comment]
Stickers received.
![IMG_20231123_153908](https://github.com/json-schema-org/community/assets/40007659/e72b4a5a-cb05-420a-871b-8e6ff002a387)

**Comment by benjagm** [comment]
These are the designs for the stand-up banner and the beer mats.

![Stand up Banner API Days (1)](https://github.com/json-schema-org/community/assets/40007659/100f0061-dca5-489f-b7c5-1fb21e85c64c)
![Build more  Break less  Empower others](https://github.com/json-schema-org/community/assets/40007659/2771f50e-201e-4bae-ba84-8c401686f4d4)

**Comment by Relequestual** [comment]
Coasters / beer mats!

![IMG_3312](https://github.com/json-schema-org/community/assets/731158/59a10a00-c4a9-4aa1-b5b7-2de36c00b1ce)

**Comment by benjagm** [comment]
![IMG_20231128_152227](https://github.com/json-schema-org/community/assets/40007659/2f1426ff-26aa-4bc6-962d-ffc6538a5782)

**Comment by benjagm** [comment]
Blog in progress in this PR: https://github.com/json-schema-org/website/pull/260

**Comment by benjagm** [comment]
We have reached out to all the contacts made. We can close this issue as completed.
