### ISSUE TITLE
Refine the website/front-end contribution experience

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#551]
As part of the roadmap, we have a goal defined to https://github.com/json-schema-org/community/issues/410 which will affect to all the contribution journeys. This issue is intended to contain the works required to refine the website/fron-end experience.

Tasks:

Completing this work will mean:
- [x] Review the Readme or equivalent.
- [x] The main place with the link to contribute.
- [x] Repo shield badges.
- [x] Review the contributing guide or equivalent and improve if necessary
- [x] Review triage.
- [x] All contributors are visible and aligned
- [x] Review all the places where this contribution path is enabled and make it consistent
- [x] Issues are triage and label issues
- [x] Issues are easy to find and progress is easy to follow.

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

**Comment by benjagm** [comment]
Completed.
