### ISSUE TITLE
Refine the community contributor experience

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#583]
As part of the roadmap, we have a goal defined to https://github.com/json-schema-org/community/issues/410 which will affect to all the contribution journeys. This issue is intended to contain the works required to refine the Community Contributor experience.

Tasks:

Completing this work will mean:
- [x] Review the Readme or equivalent.
- [x] The main place with the link to contribute.
- [x] Repo shield badges.
- [x] Review the contributing guide or equivalent and improve if necessary
- [x] Review triage
- [x] All contributors are visible and aligned
- [x] Review all the places where this contribution path is enabled and make it consistent
- [x] Document the role of Community Manager
- [x] Set org wide default labels: https://github.com/organizations/json-schema-org/settings/repository-defaults
- [x] Deploy labels to the required repos (Once created in one repo, you can use the github cli to [clone](https://cli.github.com/manual/gh_label_clone) them to other repos)
- [x] Add a triage label which is added for new Issues, and is added to any existing issues open that do not have any other labels.
- [x] Create a triage GitHub team and assign triage permission on all public repos (apart from the spec repo?)
Only suggestions. I will leave it up to you, and your priorities =]
- [x] Issues are triage and label issues
- [x] Issues are easy to find and progress is easy to follow.

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

**Comment by benjagm** [comment]
Completed
