### ISSUE TITLE
Implement a recognition System

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#634]
We identified that it was a challenge for contributors to know how to contribute to projects both inside and outside of the GitHub organization. This is why we refined the contribution journey with the issue #410 .

The scope of this issue is to go further and refine the recognition system.

# Scope 
The scope of this project includes:
 - Adapt the website and slack contribution experience to the enhanced version on Github.
 - Improve the recognition system.

# Objectives
The objectives of this project are:
 - Increase the total number of contributors.
 - Provide clarity on the total number of contributors including non-code contributions and repositories outside the organization.

# Plan
 - [ ] Enhance Recognition System
    - [ ] Evaluate the enhancement of the current recognition system. E.G. Use All Contributors spec
           https://github.com/orgs/json-schema-org/discussions/390
    - [ ] Page with TSC members.
    - [ ] Page with Champions Program and members.
    - [ ] Page with project maintainers
    - [ ] Workflows to recognize and praise contributions

 - [ ] Comms Plan 
    - [ ] Define comms templates to praise new contributors
    - [ ] Define comms to encourage contributions using the new contribution path.

**Comment by Zedoman** [comment]
Hi! I’m Avradeep Nayak, a student at VIT Bhopal studying Computer
Science in my final year. I am a programming enthusiast, and my expertise
lies in the MERN stack. I have created several projects on Ai ML. So please alow me to work on this issue under gsoc24.
