### ISSUE TITLE
Open Community Working Meeting 2021-11-05

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/community#71]
Open Community Working Meeting 2021-11-05 - [20:00 UTC](https://everytimezone.com/s/91ffa428)

Zoom Meeting link: https://postman.zoom.us/j/82037276001

Agenda:

| Topic | Owner | Decision/NextStep |
| -- | -- | -- |
| Review last call's action items #68 | @relequestual | 
| Rolled over: Check in on status of #57 | @Relequestual | Follow up with @karenetheridge on if she still plans to create a PR for Community Discussion #57 - Add to agenda for next call |
| Review updates to HyperSchema meta-schemas and merge PR https://github.com/json-schema-org/json-schema-org.github.io/pull/419 | @jdesrosiers | Merged |
| Review and merge PR to update docs to use HTTPS URLs https://github.com/json-schema-org/json-schema-org.github.io/pull/355 | @Relequestual | @jdesrosiers to review |
| Review our application to join the OpenJS Foundation https://github.com/json-schema-org/community/pull/93 | @Relequestual | No further comments beyond existing review from @jdesrosiers - @Relequestual to review and update |
| Case study questions https://github.com/json-schema-org/community/pull/95 | @Relequestual | Kevin (@kevinswiber) asked if we have connections at large companies. We have some but could always have more! Kevin said it looks like we have enough to start with. Kevin commented that there is often a lot of attention required to complete case studied and wondered if work could be delegated. Ben mentioned that it feels like the interested organisations are quite keen, but we would re-evlauate delegation if it becomes problematic.<br/> We will continue with thecase study questions, but with a primer for each organisation and an invite to discuss over video. Chatting is often useful to help tease out difficult questions |
| What should be on the JSON Schema site home page? https://github.com/json-schema-org/community/issues/75 | @Relequestual | There were no comments regarding the list of proposed updates to the home page. Jason suggested we should a single "getting started" guide, but agreed that we don't have the time to do that right now. @relequestual to add an issue |
| Proposed home page update https://github.com/json-schema-org/json-schema-org.github.io/pull/420 and https://github.com/json-schema-org/json-schema-org.github.io/pull/421 | @Relequestual | Jason thought the links to community update (https://github.com/json-schema-org/json-schema-org.github.io/pull/420) looked good.<br/> Jason thought that we should re-phrase "twice yearly release cycle" to avoid making it look like we do two major updates a year. Ben noted there is clarification, but agreed that people often don't read details. We agreed to see if this could be re-phrased to make it clearer, such as saying we do one major release a year, and another release which is a patch release. @relequestual to update PR.<br/> Jason noted the "path to standardization" section was out of date. @relequestual to add an issue to review and update |

AOB?
From @jdesrosiers 

- json-schema-org/json-schema-spec#1137 - IRI - Merged!
- json-schema-org/json-schema-spec#1139 - Dynamic reference updates
- json-schema-org/json-schema-spec#1143 - propertyDependencies
- json-schema-org/json-schema-spec#1144 - requireAllExcept
- json-schema-org/understanding-json-schema#179 - unevaluatedProperties documentation

Notes regarding AOB PRs

json-schema-org/json-schema-spec#1139 - Jason to review the PR and resolve conflicts. Jason wanted to make sure people didn't get suprised by this changed. Ben to raise the profile of this change to make it less suprising. Ben suggested Jason could write a blog article. Jason commented there wouldn't be more to say than is in the issue.

json-schema-org/json-schema-spec#1143 - This would sort of be "discriminator done properly". Greg (in the related issue) didn't have enough power. Ben and Jason felt the simplicity was good and solved the most common problems. Ben noted (as Greg had) that you cannot use non-string values. Ben suggested another structure, however Jason commented that other options were considered and documented in the issue (https://github.com/json-schema-org/json-schema-spec/issues/1082#issuecomment-806068930). Ben suggested an approach, but it was hard to communicate. @relequestual to read spec issue https://github.com/json-schema-org/json-schema-spec/issues/1082, feedback, and show an example of his proposed structure.

Action items:
- [x] Follow up with @karenetheridge re #57  - @Relequestual 
- [x] Review https://github.com/json-schema-org/json-schema-org.github.io/pull/355 - @jdesrosiers 
- [x] Update PR https://github.com/json-schema-org/community/pull/93 based on review - @Relequestual 
- [x] Add website issue to unify "getting started" guide - @Relequestual 
- [x] Merge https://github.com/json-schema-org/json-schema-org.github.io/pull/420 - @Relequestual 
- [x] Revise https://github.com/json-schema-org/json-schema-org.github.io/pull/421 based on feedback - @Relequestual 
- [ ] Add website issue to review and update "path to standardization" section - @Relequestual 
- [x] Review conflicts for json-schema-org/json-schema-spec#1139 - @jdesrosiers 
- [x] Promote the change of json-schema-org/json-schema-spec#1139 - @Relequestual 
- [x] Read Issue https://github.com/json-schema-org/json-schema-spec/issues/1082 and show example of proposal - @Relequestual  
- [x] Review json-schema-org/json-schema-spec#1144 - @Relequestual 
- [x] Review json-schema-org/understanding-json-schema#179 - @Relequestual 

Notes:

Agenda Items rolling over:
- Check in on status of #57
- Is anyone willing to take ownership over Issues and PRs in the [2020-12 draft-patch milestone](https://github.com/json-schema-org/json-schema-spec/milestone/9)?

Recording: [Full recording](https://postman.zoom.us/rec/share/SzgCG-w2BQZqg0JrtOtn_Se3g5mALVgqPtNr5KwEwKfpMtotsVcwPIc67COon7W3.T8HCsyRzfWLQaoRL?startTime=1636142571000)

**Comment by jdesrosiers** [comment]
A few PRs to call attention to ...

https://github.com/json-schema-org/json-schema-spec/pull/1137 - IRI
https://github.com/json-schema-org/json-schema-spec/pull/1139 - Dynamic reference updates
https://github.com/json-schema-org/json-schema-spec/pull/1143 - propertyDependencies
https://github.com/json-schema-org/json-schema-spec/pull/1144 - requireAllExcept
https://github.com/json-schema-org/understanding-json-schema/pull/179 - `unevaluatedProperties` documentation

**Comment by benjagm** [comment]
Closing this issue as all tasks are completed. Thanks for your contributions!

**Comment by benjagm** [comment]
Closed as completed
