### ISSUE TITLE
Ben Hutton's (@relequestual) 2021 Q4 Key Results

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/community#72]
These are my personal "key results" for 2021 Q4.
I'm putting them here and testing how easy it is to use GitHub Projects and Issues to manage them.
The method for this is using Objective Key Results (OKRs) loosely as defined in the [Atlassian playbook](https://www.atlassian.com/team-playbook/plays/okrs).

- [x] json-schema-org/community#73
- [x] json-schema-org/json-schema-spec#1191
- [x] json-schema-org/community#76
- [x] json-schema-org/community#75
- [ ] json-schema-org/community#77
- [x] json-schema-org/website#316
- [x] json-schema-org/website#317
- [x] json-schema-org/community#80
- [ ] json-schema-org/community#81
- [x] json-schema-org/community#82
- [x] json-schema-org/community#83
- [x] json-schema-org/community#84
- [ ] json-schema-org/community#85
- [ ] json-schema-org/community#86

You can also now see this list as a public project: https://github.com/orgs/json-schema-org/projects/3

**Comment by benjagm** [comment]
Is it ok to close this issue @Relequestual ?
