### ISSUE TITLE
Revamp the website home page

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/community#75]
We've known for a [LONG TIME ](https://github.com/json-schema-org/json-schema-org.github.io/issues/1) that the website needs updating. Short of a full rewrite (which is on the cards for another time), we WOULD benefit from updating just the home page.

The home page should be a launchpad for our resources and community.
We should make sure it includes:

- [x] json-schema-org/community#97
- [x] json-schema-org/community#98
- [x] json-schema-org/community#99
- [x] json-schema-org/community#100
- [x] json-schema-org/community#101
- [x] json-schema-org/community#102
- [x] json-schema-org/community#103
- [x] json-schema-org/website#235
- [x] Table of contense

Happy to take additional suggestions.
I'll create a GitHub Discussion to facilitate.

**Comment by benjagm** [comment]
Closed as complete.
